# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '动画更新masonary' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 动画更新masonary

  target '动画更新masonaryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '动画更新masonaryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
